services:
  translator-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: discord-translator-bot-dev
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: unless-stopped
