"""Initial migration: users, user_stats, translation_logs

Revision ID: 14e0e20140cd
Revises: 
Create Date: 2025-12-17 21:47:42.747223

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14e0e20140cd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("source_language", sa.String(length=50), nullable=True),
        sa.Column("target_language", sa.String(length=50), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=False),
        sa.Column("translation_type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translation_logs_created_at"),
        "translation_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_translation_logs_user_id"),
        "translation_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("translations_requested", sa.Integer(), nullable=False),
        sa.Column("translations_provided", sa.Integer(), nullable=False),
        sa.Column("messages_sent", sa.Integer(), nullable=False),
        sa.Column("commands_used", sa.Integer(), nullable=False),
        sa.Column("last_translation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("discriminator", sa.String(length=10), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_translation_logs_user_id"), table_name="translation_logs")
    op.drop_index(op.f("ix_translation_logs_created_at"), table_name="translation_logs")
    op.drop_table("translation_logs")
    # ### end Alembic commands ###
