"""Add player_lookup_logs table

Revision ID: 640db306b025
Revises: 14e0e20140cd
Create Date: 2025-12-17 22:00:45.475514

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "640db306b025"
down_revision: Union[str, None] = "14e0e20140cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_lookup_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("player_id", sa.String(length=255), nullable=False),
        sa.Column("player_name", sa.String(length=255), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_lookup_logs_created_at"),
        "player_lookup_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_lookup_logs_player_id"),
        "player_lookup_logs",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_lookup_logs_user_id"),
        "player_lookup_logs",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "translation_logs",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "original_text",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "translated_text",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "ix_translation_logs_created_at",
        table_name="translation_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_translation_logs_created_at"),
        "translation_logs",
        ["created_at"],
        unique=False,
    )
    op.drop_index(
        "ix_translation_logs_user_id",
        table_name="translation_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_translation_logs_user_id"),
        "translation_logs",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "user_stats",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "last_translation_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user_stats",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_user_stats_user_id", table_name="user_stats", postgresql_using="prefix")
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=False)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.create_index(
        "ix_user_stats_user_id",
        "user_stats",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "user_stats",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "last_translation_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_stats",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_translation_logs_user_id"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_user_id",
        "translation_logs",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_translation_logs_created_at"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_created_at",
        "translation_logs",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "translation_logs",
        "translated_text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "original_text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "guild_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_player_lookup_logs_user_id"), table_name="player_lookup_logs")
    op.drop_index(op.f("ix_player_lookup_logs_player_id"), table_name="player_lookup_logs")
    op.drop_index(op.f("ix_player_lookup_logs_created_at"), table_name="player_lookup_logs")
    op.drop_table("player_lookup_logs")
    # ### end Alembic commands ###
