"""Add foreign keys and player kingdom/castle_level

Revision ID: 701b3849f0fd
Revises: 640db306b025
Create Date: 2025-12-17 22:08:50.396408

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "701b3849f0fd"
down_revision: Union[str, None] = "640db306b025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename player_id to kingshot_id and player_name to kingshot_name
    op.alter_column("player_lookup_logs", "player_id", new_column_name="kingshot_id")
    op.alter_column("player_lookup_logs", "player_name", new_column_name="kingshot_name")

    # Add new columns
    op.add_column("player_lookup_logs", sa.Column("kingdom", sa.String(length=100), nullable=True))
    op.add_column("player_lookup_logs", sa.Column("castle_level", sa.Integer(), nullable=True))
    op.alter_column(
        "player_lookup_logs", "user_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    op.alter_column(
        "player_lookup_logs", "guild_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "player_lookup_logs", "channel_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "player_lookup_logs",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_player_lookup_logs_player_id", table_name="player_lookup_logs", postgresql_using="prefix")
    op.create_index(op.f("ix_player_lookup_logs_kingshot_id"), "player_lookup_logs", ["kingshot_id"], unique=False)
    op.drop_index("ix_player_lookup_logs_created_at", table_name="player_lookup_logs", postgresql_using="prefix")
    op.create_index(op.f("ix_player_lookup_logs_created_at"), "player_lookup_logs", ["created_at"], unique=False)
    op.drop_index("ix_player_lookup_logs_user_id", table_name="player_lookup_logs", postgresql_using="prefix")
    op.create_index(op.f("ix_player_lookup_logs_user_id"), "player_lookup_logs", ["user_id"], unique=False)
    op.create_foreign_key(None, "player_lookup_logs", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "translation_logs", "user_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    op.alter_column(
        "translation_logs", "guild_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "translation_logs", "channel_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "translation_logs", "original_text", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False
    )
    op.alter_column(
        "translation_logs", "translated_text", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_translation_logs_created_at", table_name="translation_logs", postgresql_using="prefix")
    op.create_index(op.f("ix_translation_logs_created_at"), "translation_logs", ["created_at"], unique=False)
    op.drop_index("ix_translation_logs_user_id", table_name="translation_logs", postgresql_using="prefix")
    op.create_index(op.f("ix_translation_logs_user_id"), "translation_logs", ["user_id"], unique=False)
    op.create_foreign_key(None, "translation_logs", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column("user_stats", "user_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    op.alter_column(
        "user_stats",
        "last_translation_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user_stats",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_user_stats_user_id", table_name="user_stats", postgresql_using="prefix")
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=False)
    op.create_foreign_key(None, "user_stats", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.drop_constraint(None, "user_stats", type_="foreignkey")
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.create_index(
        "ix_user_stats_user_id", "user_stats", [sa.text("user_id NULLS FIRST")], unique=False, postgresql_using="prefix"
    )
    op.alter_column(
        "user_stats",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_stats",
        "last_translation_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column("user_stats", "user_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_constraint(None, "translation_logs", type_="foreignkey")
    op.drop_index(op.f("ix_translation_logs_user_id"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_user_id",
        "translation_logs",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_translation_logs_created_at"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_created_at",
        "translation_logs",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "translation_logs", "translated_text", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False
    )
    op.alter_column(
        "translation_logs", "original_text", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False
    )
    op.alter_column(
        "translation_logs", "channel_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "translation_logs", "guild_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "translation_logs", "user_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    # Rename columns back
    op.alter_column("player_lookup_logs", "kingshot_id", new_column_name="player_id")
    op.alter_column("player_lookup_logs", "kingshot_name", new_column_name="player_name")

    op.drop_constraint(None, "player_lookup_logs", type_="foreignkey")
    op.drop_index(op.f("ix_player_lookup_logs_kingshot_id"), table_name="player_lookup_logs")
    op.drop_index(op.f("ix_player_lookup_logs_user_id"), table_name="player_lookup_logs")
    op.create_index(
        "ix_player_lookup_logs_user_id",
        "player_lookup_logs",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_player_lookup_logs_created_at"), table_name="player_lookup_logs")
    op.create_index(
        "ix_player_lookup_logs_created_at",
        "player_lookup_logs",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.create_index(
        "ix_player_lookup_logs_player_id",
        "player_lookup_logs",
        [sa.text("player_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "player_lookup_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "player_lookup_logs", "channel_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "player_lookup_logs", "guild_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "player_lookup_logs", "user_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.drop_column("player_lookup_logs", "castle_level")
    op.drop_column("player_lookup_logs", "kingdom")
    # ### end Alembic commands ###
