"""Add GiftCode table

Revision ID: cbc56878cd34
Revises: fbc1c0b29d1b
Create Date: 2026-03-15 07:35:58.417577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc56878cd34'
down_revision: Union[str, None] = 'fbc1c0b29d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_api', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_codes_code'), 'gift_codes', ['code'], unique=True)
    op.alter_column('gift_code_redemptions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('gift_code_redemptions', 'guild_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'channel_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'response_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_gift_code_redemptions_created_at', table_name='gift_code_redemptions', postgresql_using='prefix')
    op.create_index(op.f('ix_gift_code_redemptions_created_at'), 'gift_code_redemptions', ['created_at'], unique=False)
    op.drop_index('ix_gift_code_redemptions_gift_code', table_name='gift_code_redemptions', postgresql_using='prefix')
    op.create_index(op.f('ix_gift_code_redemptions_gift_code'), 'gift_code_redemptions', ['gift_code'], unique=False)
    op.drop_index('ix_gift_code_redemptions_player_id', table_name='gift_code_redemptions', postgresql_using='prefix')
    op.create_index(op.f('ix_gift_code_redemptions_player_id'), 'gift_code_redemptions', ['player_id'], unique=False)
    op.drop_index('ix_gift_code_redemptions_user_id', table_name='gift_code_redemptions', postgresql_using='prefix')
    op.create_index(op.f('ix_gift_code_redemptions_user_id'), 'gift_code_redemptions', ['user_id'], unique=False)
    op.alter_column('ocr_requests', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('ocr_requests', 'guild_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'channel_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_ocr_requests_created_at', table_name='ocr_requests', postgresql_using='prefix')
    op.create_index(op.f('ix_ocr_requests_created_at'), 'ocr_requests', ['created_at'], unique=False)
    op.drop_index('ix_ocr_requests_ocr_type', table_name='ocr_requests', postgresql_using='prefix')
    op.create_index(op.f('ix_ocr_requests_ocr_type'), 'ocr_requests', ['ocr_type'], unique=False)
    op.drop_index('ix_ocr_requests_user_id', table_name='ocr_requests', postgresql_using='prefix')
    op.create_index(op.f('ix_ocr_requests_user_id'), 'ocr_requests', ['user_id'], unique=False)
    op.alter_column('ocr_results', 'raw_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ocr_results', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ocr_results', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_ocr_results_ocr_request_id', table_name='ocr_results', postgresql_using='prefix')
    op.create_index(op.f('ix_ocr_results_ocr_request_id'), 'ocr_results', ['ocr_request_id'], unique=False)
    op.alter_column('player_lookup_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('player_lookup_logs', 'guild_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('player_lookup_logs', 'channel_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('player_lookup_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_player_lookup_logs_created_at', table_name='player_lookup_logs', postgresql_using='prefix')
    op.create_index(op.f('ix_player_lookup_logs_created_at'), 'player_lookup_logs', ['created_at'], unique=False)
    op.drop_index('ix_player_lookup_logs_kingshot_id', table_name='player_lookup_logs', postgresql_using='prefix')
    op.create_index(op.f('ix_player_lookup_logs_kingshot_id'), 'player_lookup_logs', ['kingshot_id'], unique=False)
    op.drop_index('ix_player_lookup_logs_user_id', table_name='player_lookup_logs', postgresql_using='prefix')
    op.create_index(op.f('ix_player_lookup_logs_user_id'), 'player_lookup_logs', ['user_id'], unique=False)
    op.alter_column('registered_players', 'added_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('registered_players', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('registered_players', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_registered_players_enabled', table_name='registered_players', postgresql_using='prefix')
    op.create_index(op.f('ix_registered_players_enabled'), 'registered_players', ['enabled'], unique=False)
    op.drop_index('ix_registered_players_player_id', table_name='registered_players', postgresql_using='prefix')
    op.create_index(op.f('ix_registered_players_player_id'), 'registered_players', ['player_id'], unique=True)
    op.alter_column('translation_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('translation_logs', 'guild_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('translation_logs', 'channel_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('translation_logs', 'original_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('translation_logs', 'translated_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('translation_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_translation_logs_created_at', table_name='translation_logs', postgresql_using='prefix')
    op.create_index(op.f('ix_translation_logs_created_at'), 'translation_logs', ['created_at'], unique=False)
    op.drop_index('ix_translation_logs_user_id', table_name='translation_logs', postgresql_using='prefix')
    op.create_index(op.f('ix_translation_logs_user_id'), 'translation_logs', ['user_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
    op.alter_column('users', 'joined_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_seen',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
    op.drop_index(op.f('ix_translation_logs_user_id'), table_name='translation_logs')
    op.create_index('ix_translation_logs_user_id', 'translation_logs', [sa.text('user_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_translation_logs_created_at'), table_name='translation_logs')
    op.create_index('ix_translation_logs_created_at', 'translation_logs', [sa.text('created_at NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('translation_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('translation_logs', 'translated_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('translation_logs', 'original_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('translation_logs', 'channel_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('translation_logs', 'guild_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('translation_logs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_registered_players_player_id'), table_name='registered_players')
    op.create_index('ix_registered_players_player_id', 'registered_players', [sa.text('player_id NULLS FIRST')], unique=True, postgresql_using='prefix')
    op.drop_index(op.f('ix_registered_players_enabled'), table_name='registered_players')
    op.create_index('ix_registered_players_enabled', 'registered_players', [sa.text('enabled NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('registered_players', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('registered_players', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('registered_players', 'added_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_player_lookup_logs_user_id'), table_name='player_lookup_logs')
    op.create_index('ix_player_lookup_logs_user_id', 'player_lookup_logs', [sa.text('user_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_player_lookup_logs_kingshot_id'), table_name='player_lookup_logs')
    op.create_index('ix_player_lookup_logs_kingshot_id', 'player_lookup_logs', [sa.text('kingshot_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_player_lookup_logs_created_at'), table_name='player_lookup_logs')
    op.create_index('ix_player_lookup_logs_created_at', 'player_lookup_logs', [sa.text('created_at NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('player_lookup_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('player_lookup_logs', 'channel_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('player_lookup_logs', 'guild_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('player_lookup_logs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ocr_results_ocr_request_id'), table_name='ocr_results')
    op.create_index('ix_ocr_results_ocr_request_id', 'ocr_results', [sa.text('ocr_request_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('ocr_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_results', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ocr_results', 'raw_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ocr_requests_user_id'), table_name='ocr_requests')
    op.create_index('ix_ocr_requests_user_id', 'ocr_requests', [sa.text('user_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_ocr_requests_ocr_type'), table_name='ocr_requests')
    op.create_index('ix_ocr_requests_ocr_type', 'ocr_requests', [sa.text('ocr_type NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_ocr_requests_created_at'), table_name='ocr_requests')
    op.create_index('ix_ocr_requests_created_at', 'ocr_requests', [sa.text('created_at NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('ocr_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_requests', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'channel_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'guild_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ocr_requests', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_gift_code_redemptions_user_id'), table_name='gift_code_redemptions')
    op.create_index('ix_gift_code_redemptions_user_id', 'gift_code_redemptions', [sa.text('user_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_gift_code_redemptions_player_id'), table_name='gift_code_redemptions')
    op.create_index('ix_gift_code_redemptions_player_id', 'gift_code_redemptions', [sa.text('player_id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_gift_code_redemptions_gift_code'), table_name='gift_code_redemptions')
    op.create_index('ix_gift_code_redemptions_gift_code', 'gift_code_redemptions', [sa.text('gift_code NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_gift_code_redemptions_created_at'), table_name='gift_code_redemptions')
    op.create_index('ix_gift_code_redemptions_created_at', 'gift_code_redemptions', [sa.text('created_at NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('gift_code_redemptions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gift_code_redemptions', 'response_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'channel_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'guild_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('gift_code_redemptions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_gift_codes_code'), table_name='gift_codes')
    op.drop_table('gift_codes')
    # ### end Alembic commands ###
