"""add_registered_players_table

Revision ID: d70e1e5fe277
Revises: 11b0224ef9ae
Create Date: 2025-12-25 12:44:05.099796

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d70e1e5fe277"
down_revision: Union[str, None] = "11b0224ef9ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registered_players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.String(length=255), nullable=False),
        sa.Column("player_name", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("added_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registered_players_enabled"),
        "registered_players",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_players_player_id"),
        "registered_players",
        ["player_id"],
        unique=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "gift_code_redemptions",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "response_message",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "ix_gift_code_redemptions_created_at",
        table_name="gift_code_redemptions",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_gift_code_redemptions_created_at"),
        "gift_code_redemptions",
        ["created_at"],
        unique=False,
    )
    op.drop_index(
        "ix_gift_code_redemptions_gift_code",
        table_name="gift_code_redemptions",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_gift_code_redemptions_gift_code"),
        "gift_code_redemptions",
        ["gift_code"],
        unique=False,
    )
    op.drop_index(
        "ix_gift_code_redemptions_player_id",
        table_name="gift_code_redemptions",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_gift_code_redemptions_player_id"),
        "gift_code_redemptions",
        ["player_id"],
        unique=False,
    )
    op.drop_index(
        "ix_gift_code_redemptions_user_id",
        table_name="gift_code_redemptions",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_gift_code_redemptions_user_id"),
        "gift_code_redemptions",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "player_lookup_logs",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "player_lookup_logs",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "player_lookup_logs",
        "channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "player_lookup_logs",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "ix_player_lookup_logs_created_at",
        table_name="player_lookup_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_player_lookup_logs_created_at"),
        "player_lookup_logs",
        ["created_at"],
        unique=False,
    )
    op.drop_index(
        "ix_player_lookup_logs_kingshot_id",
        table_name="player_lookup_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_player_lookup_logs_kingshot_id"),
        "player_lookup_logs",
        ["kingshot_id"],
        unique=False,
    )
    op.drop_index(
        "ix_player_lookup_logs_user_id",
        table_name="player_lookup_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_player_lookup_logs_user_id"),
        "player_lookup_logs",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "translation_logs",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "original_text",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "translated_text",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "ix_translation_logs_created_at",
        table_name="translation_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_translation_logs_created_at"),
        "translation_logs",
        ["created_at"],
        unique=False,
    )
    op.drop_index(
        "ix_translation_logs_user_id",
        table_name="translation_logs",
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_translation_logs_user_id"),
        "translation_logs",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_seen",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "joined_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("unique_rowid()"),
    )
    op.drop_index(op.f("ix_translation_logs_user_id"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_user_id",
        "translation_logs",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_translation_logs_created_at"), table_name="translation_logs")
    op.create_index(
        "ix_translation_logs_created_at",
        "translation_logs",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "translation_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "translation_logs",
        "translated_text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "original_text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "translation_logs",
        "channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "guild_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "translation_logs",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_player_lookup_logs_user_id"), table_name="player_lookup_logs")
    op.create_index(
        "ix_player_lookup_logs_user_id",
        "player_lookup_logs",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_player_lookup_logs_kingshot_id"), table_name="player_lookup_logs")
    op.create_index(
        "ix_player_lookup_logs_kingshot_id",
        "player_lookup_logs",
        [sa.text("kingshot_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_player_lookup_logs_created_at"), table_name="player_lookup_logs")
    op.create_index(
        "ix_player_lookup_logs_created_at",
        "player_lookup_logs",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "player_lookup_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "player_lookup_logs",
        "channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "player_lookup_logs",
        "guild_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "player_lookup_logs",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_gift_code_redemptions_user_id"), table_name="gift_code_redemptions")
    op.create_index(
        "ix_gift_code_redemptions_user_id",
        "gift_code_redemptions",
        [sa.text("user_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_gift_code_redemptions_player_id"), table_name="gift_code_redemptions")
    op.create_index(
        "ix_gift_code_redemptions_player_id",
        "gift_code_redemptions",
        [sa.text("player_id NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_gift_code_redemptions_gift_code"), table_name="gift_code_redemptions")
    op.create_index(
        "ix_gift_code_redemptions_gift_code",
        "gift_code_redemptions",
        [sa.text("gift_code NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.drop_index(op.f("ix_gift_code_redemptions_created_at"), table_name="gift_code_redemptions")
    op.create_index(
        "ix_gift_code_redemptions_created_at",
        "gift_code_redemptions",
        [sa.text("created_at NULLS FIRST")],
        unique=False,
        postgresql_using="prefix",
    )
    op.alter_column(
        "gift_code_redemptions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "gift_code_redemptions",
        "response_message",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "guild_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gift_code_redemptions",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_registered_players_player_id"), table_name="registered_players")
    op.drop_index(op.f("ix_registered_players_enabled"), table_name="registered_players")
    op.drop_table("registered_players")
    # ### end Alembic commands ###
